### PR TITLE
better man-page support for pre-formatted code and bullet lists

### PR DESCRIPTION
**Pull request by blampe**
This fixes some mis-alignment issues I noticed with our example code. Basically now if we start a line with a tab we'll try to re-write it in a more groff-friendly way.

I think the version of `man2html` that I'm using doesn't correctly support UTF-8 because it's messing up the charset.

@prashantv

### CODE REVIEW

**Comment by prashantv** [comment]
Need to figure out this `man2html` thing, before I ran a sed to fix them up (it was mainly the `--` that was affected), but I think figuring out why this is happening and fixing it is probably better, since there's a lot more strange characters now

**Comment by blampe** [comment]
Yep totally agree, I'll look into this. @prashantv what version does `man2html` give you? I see 3.0.1.

**Comment by blampe** [comment]
Take another look, it looks better from my end. I still don't like the line wrapping we're doing on the indented blocks, I might follow up with that later.

**Comment by blampe** [comment]
Scratch that, the weird characters are fixed but `man2html` now seems to be removing some sections that still show up correctly in `.1` (e.g., "Examples"). Hm.

**Comment by prashantv** [comment]
I have version 3.0.1 for `man2html` as well. The ASCII output seems good -- although you're right, some things are just completely gone. E,g. some options (like `--peer` and `--service`) are just missing completely. Let me see if I can reproduce that locally.

**Comment by prashantv** [comment]
Same issue with `man2html` for me. I found another converter called `mandoc`: http://mdocml.bsd.lv/ 

However, the rendered HTML is broken in different ways:
image

I'm starting to think maybe we should generate a text file and just link to that instead.

**Comment by blampe** [comment]
Sure, I'll play around with `mandoc` and `pandoc`, and if I can't get those to work I'll just generate the text file instead.

**Comment by blampe** [comment]
OK, looks much better now.

**Comment by prashantv** [comment]
This looks great! 🚢

**Comment by prashantv** [comment]
Updated the gh_pages branch, the man page looks a lot better now, thanks @blampe 
http://yarpc.github.io/yab/man.html

**Comment by breerly** [comment]
This is great, +1

On Fri, Jul 15, 2016 at 8:20 AM, Prashant Varanasi <notifications@github.com

**Pull request merged**
